export const CREATE_COURSE = "CREATE_COURSE";
export const RETRIEVE_COURSES = "RETRIEVE_COURSES";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_ALL_COURSES = "DELETE_ALL_COURSES";