export const CREATE_COURSE = 'CREATE_COURSE'
export const RETRIEVE_COURSES = 'RETRIEVE_COURSES'
export const UPDATE_COURSE = 'UPDATE_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
export const DELETE_ALL_COURSES = 'DELETE_ALL_COURSES'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const CREATE_MEMBERLIST = 'CREATE_MEMBERLIST'
export const RETRIEVE_MEMBERLIST = 'RETRIEVE_MEMBERLIST'
export const EDIT_MEMBERLIST = 'EDIT_MEMBERLIST'
export const DELETE_MEMBER = 'DELETE_MEMBER'
export const DELETE_MEMBERLIST = 'DELETE_MEMBERLIST'

export const RETRIEVE_USERS = 'RETRIEVE_USERS'

export const GET_COURSEDATES = 'GET_COURSEDATES'
export const GET_ATTENDANCEBOOK = 'GET_ATTENDANCEBOOK'
export const PUT_COURSEDATES = 'PUT_COURSEDATES'
export const PUT_ATTENDANCEBOOK = 'PUT_ATTENDANCEBOOK'
